algorithm_description: Create HLS composite
algorithm_name: hls-composite
algorithm_version: v0.1
build_command: hls-composite/build-env.sh
disk_space: 64GB
docker_container_url: mas.maap-project.org/root/maap-workspaces/custom_images/maap_base:v4.2.0
inputs:
  config: []
  positional:
  - default: ''
    description: MGRS tile identifier (e.g. 15TYK)
    name: mgrs_tile
    required: true
  - default: ''
    description: start datetime for HLS STAC query in YYYY-mm-ddTHH:MM:SSZ format
    name: start_date
    required: true
  - default: ''
    description: end datetime for HLS STAC query in YYYY-mm-ddTHH:MM:SSZ format
    name: end_date
    required: true
  - default: ''
    description: Either STAC or earthaccess to search for HLS granules
    name: search_source
    required: false
queue: maap-dps-worker-64gb
repository_url: https://github.com/zhouqiang06/hls-composite
run_command: hls-composite/run.sh

